from flask import Blueprint, render_template, Response, request, jsonify
from .. import ml_engine

ml_bp = Blueprint('ml', __name__)

@ml_bp.route('/')
def index():
    return render_template('ml/index.html')

# streaming route serves MJPEG frames generated by ml_engine
@ml_bp.route('/stream')
def stream():
    return Response(ml_engine.gen_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

@ml_bp.route('/camera/toggle', methods=['POST'])
def camera_toggle():
    try:
        # support explicit enable/disable via JSON body: {"enabled": true/false}
        data = request.get_json(silent=True) or {}
        if 'enabled' in data:
            if bool(data['enabled']):
                ml_engine.enable_capture()
            else:
                ml_engine.disable_capture()
            return jsonify({'enabled': ml_engine.is_capture_enabled()})

        # fallback: toggle when no explicit flag provided (legacy behavior)
        enabled = ml_engine.toggle_capture()
        return jsonify({'enabled': bool(enabled)})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@ml_bp.route('/camera/status')
def camera_status():
    try:
        return jsonify({'enabled': ml_engine.is_capture_enabled()})
    except Exception as e:
        return jsonify({'error': str(e)}), 500
